### ISSUE TITLE
Signing acceptance are failing due to expired profile

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#2826]
**Describe the bug**

The signing acceptance test relies on an active provisioning profile to function. The associated profile has expired a few days ago resulting in the acceptance failing.

**To Reproduce**

Run:

```sh
$ ./fourier test tuist acceptance projects/tuist/features/generate-1.feature:51
Feature: Generate a new project using Tuist (suite 1)

  Scenario: The project is an iOS application with signing (ios_app_with_signing)                                                                            # projects/tuist/features/generate-1.feature:51
    Given that tuist is available                                                                                                                            # projects/tuist/features/step_definitions/shared/tuist.rb:4
      swift build --package-path /Users/kwridan/sandbox/github/tuist
    And I have a working directory                                                                                                                           # projects/tuist/features/step_definitions/shared/workspace.rb:6
    Then I copy the fixture ios_app_with_signing into the working directory                                                                                  # projects/tuist/features/step_definitions/shared/fixtures.rb:5
    Then tuist generates the project                                                                                                                         # projects/tuist/features/step_definitions/shared/tuist.rb:8
      swift run tuist generate --path /var/folders/rh/j5qq4qnn0wbbhy4hcjk390wr0000gs/T/d20210427-71152-57xefs
      The provisioning profile SignApp.Debug has expired
       (Minitest::Assertion)
      ./projects/tuist/features/support/system.rb:9:in `system'
      ./projects/tuist/features/step_definitions/shared/tuist.rb:9:in `/^tuist generates the project$/'
      projects/tuist/features/generate-1.feature:55:in `tuist generates the project
```

**Desktop (please complete the following information):**

- Version: latest Tuist main db5d217aacc61d3ab732645c9a5175c3ceaaf754

**Notes**

- This will likely fail again in the future requiring a constant profile/certificate updates, is there a way to have a more stable version of this test?

**Comment by fortmarek** [comment]
Good catch @kwridan!

> This will likely fail again in the future requiring a constant profile/certificate updates, is there a way to have a more stable version of this test?

Yes, it is true that this would fail again in the future. I believe we could add some test-specific environment variable that would skip the check for whether the certificate is valid or not? I'll try to look into that.

**Comment by danyf90** [comment]
Looks like the test has been removed, hence I'm closing this
