### ISSUE TITLE
precompiled acceptance tests failing on main

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#5182]
### What happened?

The precompiled features acceptance tests are failing on the latest main, which is causing CI to fail for some of the active / open PRs.

### How do we reproduce it?

- Run the acceptance tests on GitHub (e.g. see https://github.com/tuist/tuist/actions/runs/4914803187/jobs/8777355188)

### Error log

```
Then I should be able to archive for iOS the scheme App                                                                             # projects/tuist/features/step_definitions/shared/xcode.rb:6
      xcodebuild -scheme App -workspace /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230508-2970-vjaccj/App.xcworkspace -destination 'platform=iOS Simulator,id=88CA0B5A-9C13-4E2A-8AF9-D88EC2023E4A' -derivedDataPath /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230508-2970-rd84d0 clean archive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""
┌──────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io/ │
      2023-05-08 14:50:12.597 xcodebuild[36515:97539] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
│                                                                          │
      2023-05-08 14:50:12.597 xcodebuild[36515:97539] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
      2023-05-08 14:50:13.944 xcodebuild[36515:97539] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-20504/IDEFoundation/Execution/RunDestinations/IDERunDestinationManager.m:1110
      Details:  There are multiple run destinations that support deployment for the current scheme; selecting anyObject: {(
          <IDERunDestination:'Any iOS Device' sdk:iphoneos15.5 variant:iphoneos arch:arm64e>,
          <IDERunDestination:'Any iOS Simulator Device' sdk:iphonesimulator15.5 variant:iphonesimulator arch:x86_64>
      )}
      Object:   <IDERunDestinationManager: 0x600001fb9940>
      Method:   -genericRunDestinationForRunDestination:scheme:schemeCommands:executionEnvironment:requiresSupportsArchiving:requiresDeploymentPlatformMatches:allowMultipleRunDestinationMatches:allowNoRunDestinationMatches:error:
      Thread:   <_NSMainThread: 0x6000010a03c0>{number = 1, name = main}
      Please file a bug at https://feedbackassistant.apple.com/ with this warning message and any useful information you can provide.
      ** ARCHIVE FAILED **
      
      
      The following build commands failed:
      	Ld /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230508-2970-rd84d0/Build/Intermediates.noindex/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/App.app/App normal (in target 'App' from project 'App')
      (1 failure)
       (Minitest::Assertion)
      ./projects/tuist/features/support/system.rb:22:in `system'
      ./projects/tuist/features/support/system.rb:27:in `xcodebuild'
```

### macOS version

12.0

### Tuist version

main

### Xcode version

13.4.1

**Comment by kwridan** [comment]
This is likely caused by https://github.com/tuist/tuist/pull/5157

 I recall a failures in the link step was encountered there, however was address and CI was all 🟢 ... will investigate why that is happening.

**Comment by kwridan** [comment]
Looking at the raw logs, looks like the same issue I originally encountered

```swift
Ld ..
2023-05-08T14:50:25.0352200Z ld: bitcode bundle could not be generated because '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230508-2970-rd84d0/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/libMyStaticLibrary.a(MyStaticLibraryComponent.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230508-2970-rd84d0/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/libMyStaticLibrary.a' for architecture arm64
2023-05-08T14:50:25.0354330Z clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kwridan** [comment]
wrong build setting was used 🤦‍♂️ - it only passed out of luck as it was flaky rather than reliably failing

```diff
- "BITCODE_ENABLED": "NO",
+ "ENABLE_BITCODE": "NO", 
```

fix pushed https://github.com/tuist/tuist/pull/5183
